"""Create contracts table

Revision ID: 7944c84239ac
Revises: e5ccbbb007a7
Create Date: 2025-04-27 14:27:11.124980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7944c84239ac'
down_revision = 'e5ccbbb007a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultant_name', sa.String(length=100), nullable=False),
    sa.Column('consultant_contact', sa.String(length=150), nullable=False),
    sa.Column('project_name', sa.String(length=150), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('time_commitment_hours', sa.Integer(), nullable=True),
    sa.Column('deliverable_milestones', sa.Text(), nullable=True),
    sa.Column('payment_rate', sa.String(length=100), nullable=True),
    sa.Column('payment_schedule', sa.String(length=100), nullable=True),
    sa.Column('reporting_frequency', sa.String(length=50), nullable=True),
    sa.Column('reporting_format', sa.String(length=50), nullable=True),
    sa.Column('stakeholder_engagements', sa.String(length=200), nullable=True),
    sa.Column('stakeholder_reporting', sa.String(length=200), nullable=True),
    sa.Column('deliverable_ownership', sa.String(length=200), nullable=True),
    sa.Column('knowledge_transfer_required', sa.Boolean(), nullable=True),
    sa.Column('confidentiality_terms', sa.Text(), nullable=True),
    sa.Column('conflict_of_interest_required', sa.Boolean(), nullable=True),
    sa.Column('non_performance_penalties', sa.String(length=200), nullable=True),
    sa.Column('termination_notice_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
