"""Add many-to-many relationship between contracts and productivity drivers

Revision ID: 8d8397d12ea5
Revises: 7944c84239ac
Create Date: 2025-04-27 14:52:45.184422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8397d12ea5'
down_revision = '7944c84239ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_driver_link',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['productivity_driver.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'driver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_driver_link')
    # ### end Alembic commands ###
