"""Extend User model with life profile

Revision ID: bd5ce4a0b1ce
Revises: 492f54c1b8da
Create Date: 2025-04-27 17:51:22.170095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5ce4a0b1ce'
down_revision = '492f54c1b8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('honors', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('life_areas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('life_priorities_2025', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('life_priorities_2030', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_interaction_style', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('daily_rhythm', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('long_term_integration', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dynamic_growth_allowed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dynamic_growth_allowed')
        batch_op.drop_column('long_term_integration')
        batch_op.drop_column('daily_rhythm')
        batch_op.drop_column('preferred_interaction_style')
        batch_op.drop_column('life_priorities_2030')
        batch_op.drop_column('life_priorities_2025')
        batch_op.drop_column('life_areas')
        batch_op.drop_column('honors')

    # ### end Alembic commands ###
